import { MongoClient, ObjectId } from "mongodb";
import dotenv from "dotenv";


dotenv.config();


const url = process.env.MONGO_URI;

if (!url) {
  console.error("❌ Error: MONGO_URI is not defined in your .env file!");
  process.exit(1);
}

const rooms = [
  {
    hotelId: new ObjectId("682a1f2b3c4d5e6f7a8b9c01"),
    roomNumber: "101",
    roomType: "Deluxe Double",
    suitetype: "Standard Suite",
    roomDescription: "Spacious deluxe room with premium bedding and a private balcony overlooking the resort gardens.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 350,
    bedType: "King Bed",
    floorNumber: 1,
    viewType: "garden",
    basePrice: 140,
    pricePerNight: 140,
    weekendPrice: 160,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Free cancellation up to 48 hours before check-in.",
    amenities: ["Tea/Coffee Maker", "Flat-screen TV", "Mini Fridge", "Work Desk"],
    specialFeatures: ["Welcome drinks", "Daily housekeeping"],
    roomImages: ["https://www.cmthotel.com/images/gallery/galleryimages/fLw6W-davnj-room8-min.jpg"],
    isAccessible: true,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: true,
    hasAC: true,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 4.6,
    numberOfReviews: 85,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: new ObjectId("682a1f2b3c4d5e6f7a8b9c01"),
    roomNumber: "102",
    roomType: "Family Safari View",
    suitetype: "Executive Suite",
    roomDescription: "Larger family style accommodations offering wide window viewpoints out towards the national park buffer zones.",
    maxOccupancy: 4,
    capacity: 4,
    roomSize: 520,
    bedType: "2 Queen Beds",
    floorNumber: 1,
    viewType: "forest", 
    basePrice: 210,
    pricePerNight: 210,
    weekendPrice: 240,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Free cancellation up to 48 hours before check-in.",
    amenities: ["Living Area", "Mini Bar", "Safety Box", "Coffee Table"],
    specialFeatures: ["Binoculars provided", "Priority booking for morning safari tours"],
    roomImages: ["https://www.cmthotel.com/images/gallery/galleryimages/GzyLG-apmgw-room7-min.jpg"],
    isAccessible: false,
    hasBathtub: true,
    hasShower: true,
    hasBalcony: true,
    hasAC: true,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: false,
    rating: 4.8,
    numberOfReviews: 42,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: new ObjectId("682a1f2b3c4d5e6f7a8b9c02"),
    roomNumber: "201",
    roomType: "Heritage Premium",
    suitetype: "Classic Royal",
    roomDescription: "Traditional Newari architecture blended with modern comforts. Features intricate hand-carved wood accents.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 410,
    bedType: "Queen Bed",
    floorNumber: 2,
    viewType: "city",
    basePrice: 110,
    pricePerNight: 110,
    weekendPrice: 130,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Non-refundable rate.",
    amenities: ["Traditional Decor", "Wardrobe", "Telephone", "Safe"],
    specialFeatures: ["Hand-carved wooden windows", "Heritage layout"],
    roomImages: ["https://via.placeholder.com/1200x800.png?text=Heritage+Room+1"],
    isAccessible: false,
    hasBathtub: true,
    hasShower: true,
    hasBalcony: false,
    hasAC: true,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 4.5,
    numberOfReviews: 44,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: new ObjectId("682a1f2b3c4d5e6f7a8b9c02"),
    roomNumber: "202",
    roomType: "King Heritage Suite",
    suitetype: "Presidential Suite",
    roomDescription: "Luxury regal suite featuring handcrafted brick linings and vintage royal design accents ideal for extended cultural vacations.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 480,
    bedType: "King Bed",
    floorNumber: 2,
    viewType: "city",
    basePrice: 160,
    pricePerNight: 160,
    weekendPrice: 185,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Cancel 7 days ahead for an eighty percent refund.",
    amenities: ["Premium Slippers", "Bathrobe", "Smart TV", "Local tea basket"],
    specialFeatures: ["Courtyard view alcove", "Complimentary traditional clay pottery gift"],
    roomImages: ["https://via.placeholder.com/1200x800.png?text=Heritage+Room+2"],
    isAccessible: true,
    hasBathtub: true,
    hasShower: true,
    hasBalcony: true,
    hasAC: true,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    numberOfReviews: 18,
    createdAt: new Date(),
    updatedAt: new Date()
  },   {
    hotelId: "682a1f2b3c4d5e6f7a8b9c03",
    roomNumber: "C10",
    roomType: "Jungle Cottage",
    suitetype: "Standard Cabin",
    roomDescription: "Thatch-roofed cottage built with local materials offering an immersive wildlife experience.",
    maxOccupancy: 3,
    capacity: 3,
    roomSize: 280,
    bedType: "1 Double, 1 Single",
    floorNumber: 0,
    viewType: "garden",
    basePrice: 85,
    pricePerNight: 85,
    weekendPrice: 95,
    taxRate: 10,
    minStayNights: 1,
    cancellationPolicy: "Cancel 7 days before arrival for a full refund.",
    amenities: ["Mosquito Nets", "Private Veranda", "Bottled Water"],
    specialFeatures: ["Wake up to bird songs", "Closest to the national park border"],
    roomImages: ["https://www.penchjunglecamp.com/img/accommodation/1m.jpg"],
    isAccessible: true,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: true,
    hasAC: true,
    hasHeating: false,
    hasWifi: true,
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    numberOfReviews: 38,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: "682a1f2b3c4d5e6f7a8b9c03",
    roomNumber: "C11",
    roomType: "Riverside Jungle Tent",
    suitetype: "Luxury Glamping Tent",
    roomDescription: "Heavy-duty canvas luxury glamping accommodation resting along the Rapti River banks.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 310,
    bedType: "King Bed",
    floorNumber: 0,
    viewType: "garden",
    basePrice: 115,
    pricePerNight: 115,
    weekendPrice: 130,
    taxRate: 10,
    minStayNights: 1,
    cancellationPolicy: "Cancel 5 days out for full voucher conversion.",
    amenities: ["Lantern lighting", "Custom bamboo fans", "Insect repellent kits"],
    specialFeatures: ["Sunset river watch porch", "Direct marshland walking trails access"],
    roomImages: ["https://pix10.agoda.net/hotelImages/1193552/1129791147/579c8f4457d410a85dcda2478fbc7409.jpg?ce=2&s=414x232"],
    isAccessible: false,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: true,
    hasAC: false,
    hasHeating: false,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 4.6,
    numberOfReviews: 54,
    createdAt: new Date(),
    updatedAt: new Date()
  },
    {
    hotelId: "682a1f2b3c4d5e6f7a8b9c04",
    roomNumber: "304",
    roomType: "Sunrise Deluxe",
    suitetype: "Executive Mountain View",
    roomDescription: "Wall-to-wall glass windows offering unhindered morning sunrise views over the central Himalayan range.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 380,
    bedType: "King Bed",
    floorNumber: 3,
    viewType: "mountain",
    basePrice: 170,
    pricePerNight: 170,
    weekendPrice: 195,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Free cancellation up to 72 hours before arrival.",
    amenities: ["Heater", "Electric Kettle", "Premium Linens", "Smart TV"],
    specialFeatures: ["Sunrise view from bed", "Private glass balcony"],
    roomImages: ["https://cf.bstatic.com/xdata/images/hotel/max1024x768/773205112.jpg?k=1964a8dbc6e224757f139276cd92e48bf390c4042ff4a3b573d4068eab0c8ac9&o="],
    isAccessible: false,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: true,
    hasAC: false,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 4.9,
    numberOfReviews: 112,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: "682a1f2b3c4d5e6f7a8b9c04",
    roomNumber: "305",
    roomType: "Himalayan Twin",
    suitetype: "Standard Mountain Room",
    roomDescription: "Comfortable room optimized for trekkers, offering sweeping vistas of the snowcaps from comfortable double twin frames.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 300,
    bedType: "2 Twin Beds",
    floorNumber: 3,
    viewType: "mountain",
    basePrice: 140,
    pricePerNight: 140,
    weekendPrice: 155,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Free cancellation up to 72 hours before arrival.",
    amenities: ["Space Heater", "Warm slippers", "Tea Mug kit"],
    specialFeatures: ["Direct mountain horizon vantage points"],
    roomImages: ["https://cf.bstatic.com/xdata/images/hotel/max1024x768/773205112.jpg?k=1964a8dbc6e224757f139276cd92e48bf390c4042ff4a3b573d4068eab0c8ac9&o="],
    isAccessible: false,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: false,
    hasAC: false,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    numberOfReviews: 89,
    createdAt: new Date(),
    updatedAt: new Date()
  },
    {
    hotelId: "682a1f2b3c4d5e6f7a8b9c05",
    roomNumber: "205",
    roomType: "Premium Lakeside Single",
    suitetype: "Boutique Suite",
    roomDescription: "Elegant room combining contemporary design with stunning vistas over Phewa Lake.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 320,
    bedType: "King Bed",
    floorNumber: 2,
    viewType: "mountain",
    basePrice: 125,
    pricePerNight: 125,
    weekendPrice: 140,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Free cancellation 48 hours prior.",
    amenities: ["Mini-bar", "Coffee Station", "Hairdryer", "Sofa"],
    specialFeatures: ["Lake facing balcony", "Complimentary boat ride coupon"],
    roomImages: ["https://cf.bstatic.com/xdata/images/hotel/max1024x768/569375380.jpg?k=c8fc5081d06f11edb2d1f2846aa930dfce93376189fde3ae608ccb6d4a931581&o="],
    isAccessible: true,
    hasBathtub: true,
    hasShower: true,
    hasBalcony: true,
    hasAC: true,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 4.7,
    numberOfReviews: 93,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: "682a1f2b3c4d5e6f7a8b9c05",
    roomNumber: "206",
    roomType: "Lakeside Double",
    suitetype: "Standard Double Room",
    roomDescription: "Well-appointed standard room featuring parallel layouts and a pristine balcony setup focusing entirely on lakeside vistas.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 360,
    bedType: "Queen Bed",
    floorNumber: 2,
    viewType: "mountain",
    basePrice: 150,
    pricePerNight: 150,
    weekendPrice: 170,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Free cancellation 48 hours prior.",
    amenities: ["LED Television", "Writing station", "Compact fridge"],
    specialFeatures: ["Balcony seating sets"],
    roomImages: ["https://cdn.esewahotels.com/hotels/1726140486-1081161207.jpg"],
    isAccessible: false,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: true,
    hasAC: true,
    hasHeating: false,
    hasWifi: true,
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    numberOfReviews: 71,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: "682a1f2b3c4d5e6f7a8b9c06",
    roomNumber: "101-S",
    roomType: "Standard Single",
    suitetype: "Basic Economy",
    roomDescription: "Comfortable standard test room designed to validate straightforward application pathways.",
    maxOccupancy: 1,
    capacity: 1,
    roomSize: 180,
    bedType: "Single Bed",
    floorNumber: 1,
    viewType: "none",
    basePrice: 99,
    pricePerNight: 99,
    weekendPrice: 99,
    taxRate: 0,
    minStayNights: 1,
    cancellationPolicy: "Strict non-refundable room policy.",
    amenities: ["Desk", "Mirror", "Clothing Rack"],
    specialFeatures: ["Quiet zone"],
    roomImages: ["https://r1imghtlak.ibcdn.com/91f4610c-7318-48de-a262-7a56caa6e7be.webp?&output-quality=75"],
    isAccessible: false,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: false,
    hasAC: true,
    hasHeating: false,
    hasWifi: true,
    isActive: true,
    isFeatured: false,
    rating: 4.0,
    numberOfReviews: 5,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: "682a1f2b3c4d5e6f7a8b9c06",
    roomNumber: "102-S",
    roomType: "Variant Double",
    suitetype: "Standard Testing",
    roomDescription: "Secondary string-type database field testing template record containing typical configuration parameters.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 240,
    bedType: "Single Bed",
    floorNumber: 1,
    viewType: "none",
    basePrice: 120,
    pricePerNight: 120,
    weekendPrice: 120,
    taxRate: 5,
    minStayNights: 1,
    cancellationPolicy: "Strict non-refundable room policy.",
    amenities: ["Dual Closets", "Test desk", "Wall mirror"],
    specialFeatures: ["Extra outlet stations"],
    roomImages: ["https://r1imghtlak.ibcdn.com/91f4610c-7318-48de-a262-7a56caa6e7be.webp?&output-quality=75"],
    isAccessible: false,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: false,
    hasAC: true,
    hasHeating: false,
    hasWifi: true,
    isActive: true,
    isFeatured: false,
    rating: 4.1,
    numberOfReviews: 3,
    createdAt: new Date(),
    updatedAt: new Date()
  },
    {
    hotelId: "682a1f2b3c4d5e6f7a8b9c07",
    roomNumber: "402",
    roomType: "Executive Double",
    suitetype: "Business Standard",
    roomDescription: "Perfect corporate or leisure room located near downtown Bharatpur amenities.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 310,
    bedType: "Double Bed",
    floorNumber: 4,
    viewType: "city",
    basePrice: 95,
    pricePerNight: 95,
    weekendPrice: 105,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Cancel up to 24 hours before check-in without penalty.",
    amenities: ["High-speed Internet", "Work Chair", "LED TV", "Ironing Board"],
    specialFeatures: ["City skyline panorama", "Express laundry available"],
    roomImages: ["https://cdn.esewahotels.com/hotels/cover-1663244263-2008430746.JPG"],
    isAccessible: true,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: false,
    hasAC: true,
    hasHeating: false,
    hasWifi: true,
    isActive: true,
    isFeatured: false,
    rating: 4.4,
    numberOfReviews: 29,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: "682a1f2b3c4d5e6f7a8b9c07",
    roomNumber: "403",
    roomType: "Pauwa Club Suite",
    suitetype: "Premium Suite",
    roomDescription: "Upgraded business class environment featuring modular layouts, corporate workspaces, and superior city views.",
    maxOccupancy: 3,
    capacity: 3,
    roomSize: 420,
    bedType: "King Bed",
    floorNumber: 4,
    viewType: "city",
    basePrice: 140,
    pricePerNight: 140,
    weekendPrice: 155,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Cancel up to 24 hours before check-in without penalty.",
    amenities: ["Ergonomic Executive Chair", "Espresso Pod Station", "Plush Couch", "Robes"],
    specialFeatures: ["Complimentary lounge entry pass", "Airport pickup available"],
    roomImages: ["https://cms.hotelpauwa.com/wp-content/uploads/2025/10/Frame-1-35.jpg"],
    isAccessible: false,
    hasBathtub: true,
    hasShower: true,
    hasBalcony: true,
    hasAC: true,
    hasHeating: false,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 4.7,
    numberOfReviews: 14,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: "682a1f2b3c4d5e6f7a8b9c11",
    roomNumber: "G-12",
    roomType: "Twin Bed Garden Room",
    suitetype: "Lush Comfort Deluxe",
    roomDescription: "Bright, expansive room featuring glass doors that walk straight out onto beautiful manicured lawns.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 400,
    bedType: "2 Twin Beds",
    floorNumber: 0,
    viewType: "garden",
    basePrice: 1500,
    pricePerNight: 1500,
    weekendPrice: 1500,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Free cancellation within 48 hours of booking.",
    amenities: ["Flat-screen TV", "Air Conditioning", "Sofa set", "Wardrobe"],
    specialFeatures: ["Direct garden entry terrace", "Soundproofed rooms"],
    roomImages: ["https://cdn.esewahotels.com/hotels/1669957030-108704049.jpeg"],
    isAccessible: true,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: true,
    hasAC: true,
    hasHeating: false,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 4.5,
    numberOfReviews: 67,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: "682a1f2b3c4d5e6f7a8b9c11",
    roomNumber: "G-14",
    roomType: "Honeymoon King Villa",
    suitetype: "Luxury Garden Suite",
    roomDescription: "Secluded resort room variant focusing on deep privacy, luxury standalone configurations, and pristine landscaped view vectors.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 550,
    bedType: "King Bed",
    floorNumber: 0,
    viewType: "garden",
    basePrice: 2500,
    pricePerNight: 2500,
    weekendPrice: 2800,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Free cancellation within 48 hours of booking.",
    amenities: ["Outdoor rain shower setup", "Large sofa lounge", "Smart Entertainment screen"],
    specialFeatures: ["Private hammock terrace", "Complimentary bottle of local fruit wine"],
    roomImages: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-bvRT34_bKO9eqHYroVUS-cIFM0ymTbc3SQ&s"],
    isAccessible: false,
    hasBathtub: true,
    hasShower: true,
    hasBalcony: true,
    hasAC: true,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 4.8,
    numberOfReviews: 33,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: "682a1f2b3c4d5e6f7a8b9c12",
    roomNumber: "P-302",
    roomType: "Riverside Pool Suite",
    suitetype: "Premium Luxury Suite",
    roomDescription: "Beautifully decorated room combining quick access to the pool deck with serene ambient sounds from the Trishuli River.",
    maxOccupancy: 4,
    capacity: 4,
    roomSize: 450,
    bedType: "King Bed",
    floorNumber: 2,
    viewType: "pool",
    basePrice: 1500,
    pricePerNight: 1500,
    weekendPrice: 1800,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Non-refundable during peak weekends.",
    amenities: ["Swimming Pool Access", "Mini Bar", "Premium sound system", "Espresso Machine"],
    specialFeatures: ["River soundscape", "Private deck chairs"],
    roomImages: ["https://cdn.esewahotels.com/hotels/1727841618-1152074193.jpg"],
    isAccessible: false,
    hasBathtub: true,
    hasShower: true,
    hasBalcony: true,
    hasAC: true,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 4.7,
    numberOfReviews: 89,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: "682a1f2b3c4d5e6f7a8b9c12",
    roomNumber: "P-304",
    roomType: "Adventure Quad Bed",
    suitetype: "Group Standard Room",
    roomDescription: "High utility cabin environment tailored for rafting groups traveling along Trishuli waters.",
    maxOccupancy: 4,
    capacity: 4,
    roomSize: 400,
    bedType: "4 Single Beds",
    floorNumber: 1,
    viewType: "pool",
    basePrice: 1800,
    pricePerNight: 1800,
    weekendPrice: 2000,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Cancel 72 hours before arrival for a partial refund.",
    amenities: ["Heavy lockers", "Multiple charging blocks", "Hydration point"],
    specialFeatures: ["Waterproof gear storage compartments"],
    roomImages: ["https://cdn.esewahotels.com/hotels/1727841110-1558181318.jpg"],
    hasBathtub: false,
    hasShower: true,
    hasBalcony: false,
    hasAC: true,
    hasHeating: false,
    hasWifi: true,
    isActive: true,
    isFeatured: false,
    rating: 4.4,
    numberOfReviews: 61,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: "682a1f2b3c4d5e6f7a8b9c13",
    roomNumber: "G-01",
    roomType: "Traditional Gurung Twin Room",
    suitetype: "Authentic Village Stay",
    roomDescription: "Cozy stone walls, traditional handmade woodwork, and unparalleled direct mountain views over the Annapurna range.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 220,
    bedType: "2 Twin Beds",
    floorNumber: 1,
    viewType: "mountain",
    basePrice: 2000,
    pricePerNight: 2000,
    weekendPrice: 2000,
    taxRate: 0,
    minStayNights: 1,
    cancellationPolicy: "Flexible 24-hour cancellation window.",
    amenities: ["Heavy Himalayan Blankets", "Slippers", "Writing Table"],
    specialFeatures: ["Direct mountain view", "Morning wake-up local organic tea served directly to room"],
    roomImages: ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/a5/3c/66/ashish-aama-homestay.jpg?w=700&h=-1&s=1"],
    isAccessible: false,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: false,
    hasAC: false,
    hasHeating: false,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 4.9,
    numberOfReviews: 76,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: "682a1f2b3c4d5e6f7a8b9c13",
    roomNumber: "G-02",
    roomType: "Aama Family Attic",
    suitetype: "Family Village Stay",
    roomDescription: "Traditional wood-framed loft attic space featuring sweeping architectural warmth and incredible family hospitality structures.",
    maxOccupancy: 3,
    capacity: 2,
    roomSize: 280,
    bedType: "2 Single Beds",
    floorNumber: 2,
    viewType: "mountain",
    basePrice: 2500,
    pricePerNight: 2500,
    weekendPrice: 2500,
    taxRate: 0,
    minStayNights: 1,
    cancellationPolicy: "Flexible 24-hour cancellation window.",
    amenities: ["Handmade quilts", "Local wool rugs", "Under-bed trunks"],
    specialFeatures: ["Highest panoramic ridge view", "Complimentary traditional Gurung dress dress-up photo session"],
    roomImages: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8qa6-HSsi2yR5gK7U7I06Piza3j9gnrYIcw&s"],
    isAccessible: false,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: true,
    hasAC: false,
    hasHeating: false,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 5.0,
    numberOfReviews: 39,
    createdAt: new Date(),
    updatedAt: new Date()
  }



];

async function run() {
  const client = new MongoClient(url);

  try {
    console.log("🔄 Connecting to MongoDB Atlas Cloud...");
    await client.connect();
    console.log("✅ Connected successfully!");

    // Automatically selects the database specified in your URI connection string path
    const db = client.db(); 
    const collection = db.collection("rooms");

    console.log("🧹 Clearing old rooms data...");
    await collection.deleteMany({});
    console.log("🗑️ Old rooms collection cleared.");

    console.log("📤 Seeding new data...");
    const result = await collection.insertMany(rooms);
    console.log(`🚀 Success! ${result.insertedCount} rooms successfully seeded to Atlas!`);
    
  } catch (err) {
    console.error("❌ Database seeding failed:", err);
  } finally {
    await client.close();
    console.log("🔌 Database connection cleanly closed.");
  }
}

run();