import { MongoClient, ObjectId } from "mongodb";
import dotenv from "dotenv";


dotenv.config();


const url = process.env.MONGO_URI;

if (!url) {
  console.error("❌ Error: MONGO_URI is not defined in your .env file!");
  process.exit(1);
}

const rooms = [
  {
    hotelId: new ObjectId("682a1f2b3c4d5e6f7a8b9c01"),
    roomNumber: "101",
    roomType: "Deluxe Double",
    suitetype: "Standard Suite",
    roomDescription: "Spacious deluxe room with premium bedding and a private balcony overlooking the resort gardens.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 350,
    bedType: "King Bed",
    floorNumber: 1,
    viewType: "garden",
    basePrice: 140,
    pricePerNight: 140,
    weekendPrice: 160,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Free cancellation up to 48 hours before check-in.",
    amenities: ["Tea/Coffee Maker", "Flat-screen TV", "Mini Fridge", "Work Desk"],
    specialFeatures: ["Welcome drinks", "Daily housekeeping"],
    roomImages: ["https://www.cmthotel.com/images/gallery/galleryimages/fLw6W-davnj-room8-min.jpg"],
    isAccessible: true,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: true,
    hasAC: true,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 4.6,
    numberOfReviews: 85,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: new ObjectId("682a1f2b3c4d5e6f7a8b9c01"),
    roomNumber: "102",
    roomType: "Family Safari View",
    suitetype: "Executive Suite",
    roomDescription: "Larger family style accommodations offering wide window viewpoints out towards the national park buffer zones.",
    maxOccupancy: 4,
    capacity: 4,
    roomSize: 520,
    bedType: "2 Queen Beds",
    floorNumber: 1,
    viewType: "forest", 
    basePrice: 210,
    pricePerNight: 210,
    weekendPrice: 240,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Free cancellation up to 48 hours before check-in.",
    amenities: ["Living Area", "Mini Bar", "Safety Box", "Coffee Table"],
    specialFeatures: ["Binoculars provided", "Priority booking for morning safari tours"],
    roomImages: ["https://www.cmthotel.com/images/gallery/galleryimages/GzyLG-apmgw-room7-min.jpg"],
    isAccessible: false,
    hasBathtub: true,
    hasShower: true,
    hasBalcony: true,
    hasAC: true,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: false,
    rating: 4.8,
    numberOfReviews: 42,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: new ObjectId("682a1f2b3c4d5e6f7a8b9c02"),
    roomNumber: "201",
    roomType: "Heritage Premium",
    suitetype: "Classic Royal",
    roomDescription: "Traditional Newari architecture blended with modern comforts. Features intricate hand-carved wood accents.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 410,
    bedType: "Queen Bed",
    floorNumber: 2,
    viewType: "city",
    basePrice: 110,
    pricePerNight: 110,
    weekendPrice: 130,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Non-refundable rate.",
    amenities: ["Traditional Decor", "Wardrobe", "Telephone", "Safe"],
    specialFeatures: ["Hand-carved wooden windows", "Heritage layout"],
    roomImages: ["https://via.placeholder.com/1200x800.png?text=Heritage+Room+1"],
    isAccessible: false,
    hasBathtub: true,
    hasShower: true,
    hasBalcony: false,
    hasAC: true,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 4.5,
    numberOfReviews: 44,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: new ObjectId("682a1f2b3c4d5e6f7a8b9c02"),
    roomNumber: "202",
    roomType: "King Heritage Suite",
    suitetype: "Presidential Suite",
    roomDescription: "Luxury regal suite featuring handcrafted brick linings and vintage royal design accents ideal for extended cultural vacations.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 480,
    bedType: "King Bed",
    floorNumber: 2,
    viewType: "city",
    basePrice: 160,
    pricePerNight: 160,
    weekendPrice: 185,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Cancel 7 days ahead for an eighty percent refund.",
    amenities: ["Premium Slippers", "Bathrobe", "Smart TV", "Local tea basket"],
    specialFeatures: ["Courtyard view alcove", "Complimentary traditional clay pottery gift"],
    roomImages: ["https://via.placeholder.com/1200x800.png?text=Heritage+Room+2"],
    isAccessible: true,
    hasBathtub: true,
    hasShower: true,
    hasBalcony: true,
    hasAC: true,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    numberOfReviews: 18,
    createdAt: new Date(),
    updatedAt: new Date()
  },   {
    hotelId: "682a1f2b3c4d5e6f7a8b9c03",
    roomNumber: "C10",
    roomType: "Jungle Cottage",
    suitetype: "Standard Cabin",
    roomDescription: "Thatch-roofed cottage built with local materials offering an immersive wildlife experience.",
    maxOccupancy: 3,
    capacity: 3,
    roomSize: 280,
    bedType: "1 Double, 1 Single",
    floorNumber: 0,
    viewType: "garden",
    basePrice: 85,
    pricePerNight: 85,
    weekendPrice: 95,
    taxRate: 10,
    minStayNights: 1,
    cancellationPolicy: "Cancel 7 days before arrival for a full refund.",
    amenities: ["Mosquito Nets", "Private Veranda", "Bottled Water"],
    specialFeatures: ["Wake up to bird songs", "Closest to the national park border"],
    roomImages: ["https://www.penchjunglecamp.com/img/accommodation/1m.jpg"],
    isAccessible: true,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: true,
    hasAC: true,
    hasHeating: false,
    hasWifi: true,
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    numberOfReviews: 38,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: "682a1f2b3c4d5e6f7a8b9c03",
    roomNumber: "C11",
    roomType: "Riverside Jungle Tent",
    suitetype: "Luxury Glamping Tent",
    roomDescription: "Heavy-duty canvas luxury glamping accommodation resting along the Rapti River banks.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 310,
    bedType: "King Bed",
    floorNumber: 0,
    viewType: "garden",
    basePrice: 115,
    pricePerNight: 115,
    weekendPrice: 130,
    taxRate: 10,
    minStayNights: 1,
    cancellationPolicy: "Cancel 5 days out for full voucher conversion.",
    amenities: ["Lantern lighting", "Custom bamboo fans", "Insect repellent kits"],
    specialFeatures: ["Sunset river watch porch", "Direct marshland walking trails access"],
    roomImages: ["https://pix10.agoda.net/hotelImages/1193552/1129791147/579c8f4457d410a85dcda2478fbc7409.jpg?ce=2&s=414x232"],
    isAccessible: false,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: true,
    hasAC: false,
    hasHeating: false,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 4.6,
    numberOfReviews: 54,
    createdAt: new Date(),
    updatedAt: new Date()
  },
    {
    hotelId: "682a1f2b3c4d5e6f7a8b9c04",
    roomNumber: "304",
    roomType: "Sunrise Deluxe",
    suitetype: "Executive Mountain View",
    roomDescription: "Wall-to-wall glass windows offering unhindered morning sunrise views over the central Himalayan range.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 380,
    bedType: "King Bed",
    floorNumber: 3,
    viewType: "mountain",
    basePrice: 170,
    pricePerNight: 170,
    weekendPrice: 195,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Free cancellation up to 72 hours before arrival.",
    amenities: ["Heater", "Electric Kettle", "Premium Linens", "Smart TV"],
    specialFeatures: ["Sunrise view from bed", "Private glass balcony"],
    roomImages: ["https://cf.bstatic.com/xdata/images/hotel/max1024x768/773205112.jpg?k=1964a8dbc6e224757f139276cd92e48bf390c4042ff4a3b573d4068eab0c8ac9&o="],
    isAccessible: false,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: true,
    hasAC: false,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: true,
    rating: 4.9,
    numberOfReviews: 112,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    hotelId: "682a1f2b3c4d5e6f7a8b9c04",
    roomNumber: "305",
    roomType: "Himalayan Twin",
    suitetype: "Standard Mountain Room",
    roomDescription: "Comfortable room optimized for trekkers, offering sweeping vistas of the snowcaps from comfortable double twin frames.",
    maxOccupancy: 2,
    capacity: 2,
    roomSize: 300,
    bedType: "2 Twin Beds",
    floorNumber: 3,
    viewType: "mountain",
    basePrice: 140,
    pricePerNight: 140,
    weekendPrice: 155,
    taxRate: 13,
    minStayNights: 1,
    cancellationPolicy: "Free cancellation up to 72 hours before arrival.",
    amenities: ["Space Heater", "Warm slippers", "Tea Mug kit"],
    specialFeatures: ["Direct mountain horizon vantage points"],
    roomImages: ["https://via.placeholder.com/1200x800.png?text=Mountain+View+Room+2"],
    isAccessible: false,
    hasBathtub: false,
    hasShower: true,
    hasBalcony: false,
    hasAC: false,
    hasHeating: true,
    hasWifi: true,
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    numberOfReviews: 89,
    createdAt: new Date(),
    updatedAt: new Date()
  },

];

async function run() {
  const client = new MongoClient(url);

  try {
    console.log("🔄 Connecting to MongoDB Atlas Cloud...");
    await client.connect();
    console.log("✅ Connected successfully!");

    // Automatically selects the database specified in your URI connection string path
    const db = client.db(); 
    const collection = db.collection("rooms");

    console.log("🧹 Clearing old rooms data...");
    await collection.deleteMany({});
    console.log("🗑️ Old rooms collection cleared.");

    console.log("📤 Seeding new data...");
    const result = await collection.insertMany(rooms);
    console.log(`🚀 Success! ${result.insertedCount} rooms successfully seeded to Atlas!`);
    
  } catch (err) {
    console.error("❌ Database seeding failed:", err);
  } finally {
    await client.close();
    console.log("🔌 Database connection cleanly closed.");
  }
}

run();